language: php
  - '5.5'
  - '5.6'
  - '7.0'
  - '7.1'
# Commands to be run before your environment runs.
before_script:
  - composer self-update
  - composer install --prefer-source --no-interaction --dev

script: phpunit tests
